name: bank_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.1
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: lib/assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/inter/Inter-Regular.ttf
          weight: 500
        - asset: lib/assets/fonts/inter/Inter-Medium.ttf
          weight: 400
        - asset: lib/assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/inter/Inter-Thin.ttf
          weight: 100
